[[regexes]]
  name = "Sentinel IPS: USERDATA2"
  re = '''^(?P<date>\SYSLOG_DATE)\s\d{4}-\d{2}-\d{2}\s\d{2}:\s\d{2}:\d{2}\.\d+\|(?P<srcip>\IPV4)\|(?P<srcport>\PORT)\|(?P<dstip>\IPV4)\|(?P<dstport>\PORT)\|(?P<pluginsid>\d+)\|(?P<udtwo>.*)(\s)?$'''
  hide = false
  rule_block_name = "General capture - normal format"

[[regexes]]
  name = "Sentinel IPS: USERDATA2"
  re = '''^(?P<date>\SYSLOG_DATE)\s\d{4}-\d{2}-\d{2}\s\d{2}:\s\d{2}:\d{2}\.\d+\|(?P<srcip>\IPV4)\|(?P<srcport>\PORT)\|(?P<dstip>\IPV4)\|(?P<dstport>\PORT)\|\((?P<pluginsid>\d+)\,\s+\'(?P<udtwo>.*)(\s\'|\')\)$'''
  hide = false
  rule_block_name = "General capture - odd paren. format"

[options]
  show_matches = true
  show_misses = false
  show_all_matches = false
  match_sample_size = 0
  show_multiple_matches = false

[plugin]
  id = 743182
  name = "sentinel-ips"
  version = "v1.0.0"
  description = ""
  log_file = "/var/log/sentinel-ips.log"
  website = "https://gitlab.sedara.io/av-plugins/sentinel-ips"
  log_format = "-"

[vendor]
  name = "Econet"
  model = "Sentinel IPS"
  version = "4.x"
  per_asset = false

[author]
  name = "Sedara, LLC."
  email = "devs@sedarasecurity.com"
